export const Users = [
    {
        id:1,
        profilePicture: "assets/person/1.jpg",
        username: "Qamar Abbas",
    },
    {
        id:2,
        profilePicture: "assets/person/2.jpg",
        username: "Muhammad Usman",
    },
    {
        id:3,
        profilePicture: "assets/person/3.jpg",
        username: "Allah Ditta",
    },
    {
        id:4,
        profilePicture: "assets/person/4.jpg",
        username: "Hunain Hanif",
    },
    {
        id:5,
        profilePicture: "assets/person/5.jpg",
        username: "Muhammad Shahbaz",
    },
    {
        id:6,
        profilePicture: "assets/person/6.jpg",
        username: "Afaq Ahmad",
    },
    {
        id:7,
        profilePicture: "assets/person/7.jpg",
        username: "Sherry",
    },
    {
        id:8,
        profilePicture: "assets/person/8.jpg",
        username: "Laiba",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Memory Of Last Day In University :)",
        photo: "assets/post/1.jpg",
        date: "2 Mins ago",
        userId: 1,
        like: 44,
        comment: 22,
    },
    {
        id: 2,
        desc: "Rosees are red :)",
        photo: "assets/post/2.jpg",
        date: "20 Mins ago",
        userId: 2,
        like: 20,
        comment: 2,
    },
    {
        id: 3,
        photo: "assets/post/3.jpg",
        date: "8 Mins ago",
        userId: 3,
        like: 12,
        comment: 8,
    },
    {
        id: 4,
        desc: "Nature Have Something Special",
        photo: "assets/post/4.jpg",
        date: "12 Mins ago",
        userId: 4,
        like: 23,
        comment: 15,
    },
    {
        id: 5,
        photo: "assets/post/5.png",
        date: "2 Mins ago",
        userId: 5,
        like: 55,
        comment: 28,
    },
    {
        id: 6,
        desc: "Trip With Friends like a moments of pleasure..",
        photo: "assets/post/6.jpg",
        date: "20 Mins ago",
        userId: 6,
        like: 55,
        comment: 28,
    },
    {
        id: 7,
        desc: "A developer Dream Rooom",
        photo: "assets/post/7.jpg",
        date: "20 Mins ago",
        userId: 7,
        like: 200,
        comment: 55,
    },
    {
        id: 8,
        desc: "Beautifull.....)",
        photo: "assets/post/8.png",
        date: "20 Mins ago",
        userId: 8,
        like: 3,
        comment: 2,
    },
]

